### ISSUE TITLE
Various XmonSimulator tests failing on windows

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1144]
I think they all have to do with multiprocessing. Maybe we should check the OS before using it?

```
cirq\google\sim\xmon_stepper_test.py:638 (test_large_circuit_unitary[2-True])
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "...\Anaconda3\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "...\Anaconda3\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "...\cirq\google\sim\xmon_stepper.py", line 420, in _reset_state
    _state_shard(args).fill(0)
  File ...\cirq\google\sim\xmon_stepper.py", line 390, in _state_shard
    return mem_manager.SharedMemManager.get_array(state_handle).view(
  File "...\cirq\google\sim\mem_manager.py", line 182, in get_array
    return SharedMemManager._instance._get_array(handle)
  File "...\cirq\google\sim\mem_manager.py", line 125, in _get_array
    assert tup is not None
AssertionError
"""
```

**Comment by c-poole** [comment]
I have a windows dev environment set up so I can take a look into this as well as #1143 and #813 which also contain windows specific test failures.

**Comment by vtomole** [comment]
Closed by: https://github.com/quantumlib/Cirq/pull/1549
