### ISSUE TITLE
Type cannot be coerced error on windows

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1505]
(Moved from https://github.com/quantumlib/OpenFermion-Cirq/issues/342)

On my linux machine, the following code runs to completion. But apparently it fails on Windows. @c-poole could you confirm that it fails on your machine and, if so, try to cut it down to a smaller amount of code?

Repro code:

```python
import cirq
import random
import numpy as np
import sympy
def energy_func(length,h,jr,jc):
    def energy(measurements):
        #Reshape the measurement into array that matches the grid
        meas = [measurements[i*length:(i+1)*length] for i in range(length)]
        #Converts true/false to +1/-1
        pm_meas = 1-2*np.array(meas).astype(np.int32)
        tot_E = 0
        for i, r in enumerate(jr):
            for j, jr_ij in enumerate(r):
                tot_E += jr_ij*pm_meas[i,j]*pm_meas[i+1,j]
        for i, c in enumerate(jc):
            for j, jc_ij in enumerate(c):
                tot_E += jc_ij*pm_meas[i,j]*pm_meas[i,j+1]
        tot_E += np.sum(pm_meas*h)
        return tot_E
    return energy

def obj_func(result):
    E_hist = result.histogram(key='x', fold_func=energy_func(3,h,jr,jc))
    return np.sum([k*v for k,v in E_hist.items()])/result.repetitions
#Arbitrary X rotation in a layer of the number of qubits in the grid
def rot_x_layer(lenght, half_turns):
    rot = cirq.XPowGate(exponent=half_turns)
    for i in range(lenght):
        for j in range(lenght):
            yield rot(cirq.GridQubit(i,j))
#Arbitrary Z rotation in a layer of the number of qubits in the grid for whose local transversefield is positive
def rot_z_layer(h,half_turns):
    rot = cirq.ZPowGate(exponent=half_turns)
    rows = len(h)
    cols = len(h[0])
    for i in range(rows):
        for j in range(cols):
            if (h[i][j]>0):
                yield rot(cirq.GridQubit(i,j))
#2-local operation over pairs of states with different coupling constants. A coordinated action of Zrotations if the coupling is positive and a coordinated action of a Zrotation conjugated with a Xrotation.
def rot_11_layer(jc,jr,half_turns):
    rot1 = cirq.CZPowGate(exponent=half_turns)
    rot2 = cirq.XPowGate(exponent=half_turns)
    for i, c in enumerate(jc):
        for j, jc_ij in enumerate(c):
            if jc_ij<0:
                yield(cirq.X(cirq.GridQubit(i,j)))
                yield(cirq.X(cirq.GridQubit(i,j+1)))
            yield(rot1(cirq.GridQubit(i,j),cirq.GridQubit(i,j+1)))
            if jc_ij<0:
                yield( cirq.X(cirq.GridQubit(i,j)))
                yield(cirq.X(cirq.GridQubit(i,j+1)))
    for i, r in enumerate(jr):
        for j, jr_ij in enumerate(r):
            if jr_ij<0:
                yield( cirq.X(cirq.GridQubit(i,j)))
                yield(cirq.X(cirq.GridQubit(i+1,j)))
            yield(rot1(cirq.GridQubit(i,j),cirq.GridQubit(i+1,j)))
            if jr_ij<0:
                yield(cirq.X(cirq.GridQubit(i,j)))
                yield(cirq.X(cirq.GridQubit(i+1,j)))
#Step of the construction of the anzats
def one_step(h,jc,jr,x_hs,h_hs,j_hs):
    lenght = len(h)
    yield rot_x_layer(lenght,x_hs)
    yield rot_z_layer(h,h_hs)
    yield rot_11_layer(jc,jr,j_hs)
#Gets a configuration for the Ising problem
def rand2d(rows, cols):
    return[[random.choice([+1.0,-1.0]) for _ in range(cols)] for _ in range(rows)]
#Gives a random configuration of the Ising transverse field Hamiltonian
def random_instance(lenght):
    #transverse field
    h = rand2d(lenght,lenght)
    #columns coupling constants
    jc = rand2d(lenght,lenght-1)
    #row coupling constants
    jr = rand2d(lenght-1,lenght)
    return (h,jr,jc)

#length of the grid
lenght = 3
#Define Qubits on the grid
qubits = [cirq.GridQubit(i,j) for i in range(lenght) for j in range(lenght)]
print(qubits)
circuit = cirq.Circuit()
h, jr, jc = random_instance(3)
print('Transverse field: {}'.format(h))
print('Columns coupling: {}'.format(jc))
print('Rows coupling: {}'.format(jr))
alpha = sympy.Symbol('alpha')
beta = sympy.Symbol('beta')
gamma = sympy.Symbol('gamma')
circuit.append(one_step(h,jc,jr,alpha,beta,gamma))
circuit.append(cirq.measure(*qubits,key='x'))
resolver = cirq.ParamResolver({'alpha':0.1,'beta':0.3,'gamma':0.7})
resolved_circuit = cirq.resolve_parameters(circuit,resolver)
simulator = cirq.Simulator()
print(circuit)
#We can evaluate many different values of our parameters usign sweeps and obtaining the result of the objective function
sweep = (cirq.Linspace(key='alpha', start=0.1, stop=0.9, length=5)
         * cirq.Linspace(key='beta', start=0.1, stop=0.9, length=5)
         * cirq.Linspace(key='gamma', start=0.1, stop=0.9, length=5))
results = simulator.run_sweep(circuit, params=sweep, repetitions=100)
for result in results:
    print(result.params.param_dict, obj_func(result))



'''


print(circuit)
results = simultor.run(circuit,repetitions=100)
print(results.histogram(key='x', fold_func=energy_func(lenght,h,jr,jc)))
print('Value of the objective function {}'.format(obj_func(results)))
'''

'''circuit.append([cirq.H(q) for q in qubits if (q.row+q.col)%2 == 0], strategy=cirq.InsertStrategy.EARLIEST)
circuit.append([cirq.X(q) for q in qubits if (q.row+q.col)%2 == 1], strategy=cirq.InsertStrategy.NEW_THEN_INLINE)
print(circuit)
for i,m in enumerate(circuit):
    print('Moment {}:{}'.format(i,m))
circuit.append(rot_x_layer(2,0.1))
print(circuit)'''
```

Reported error text:

```
Traceback (most recent call last):
  File "tutorial.py", line 104, in <module>
    results = simulator.run_sweep(circuit, params=sweep, repetitions=100) 
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\simulator.py", line 85, in run_sweep
    repetitions=repetitions)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 121, in _run
    return self._run_sweep_sample(resolved_circuit, repetitions)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 134, in _run_sweep_sample
    perform_measurements=False):
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 231, in _base_iterator
    indices))
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\protocols\apply_unitary.py", line 208, in apply_unitary
    result = func(args)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\ops\gate_operation.py", line 107, in _apply_unitary_
    default=NotImplemented)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\protocols\apply_unitary.py", line 222, in apply_unitary
    out=args.available_buffer)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\linalg\transformations.py", line 214, in apply_matrix_to_slices
    out[s_i] *= matrix[i, i]
TypeError: ufunc 'multiply' output (typecode 'O') could not be coerced to provided output parameter (typecode 'F') according to the casting rule ''same_kind''
```

**Comment by vtomole** [comment]
Not just windows. I run into this same error on `Ubuntu 18.04` with `Python 3.6.7`

**Comment by c-poole** [comment]
I'll have a look.

**Comment by piyush2468** [comment]
Using cirq.Circuits is somehow forcing this error while Xmon is giving attribute error of cos definition. 
Root of the problem is in Sympy most probably, I'll look into it.

**Comment by vtomole** [comment]
@HiggsBoson3310 This code is fine on cirq version `0.4.0` with `cirq.symbol`. A temporary fix would be downgrading your installed cirq version and changing calls for `sympy.symbol` to `cirq.symbol`.

**Comment by c-poole** [comment]
My windows machine runs this code without error

**Comment by Strilanc** [comment]
I believe the error is a result of applying cirq 0.5 documentation to cirq 0.4, or vice versa. Closing is not reproduceable.
