### ISSUE TITLE
Start running doctest

### ISSUE THREAD

**Issue by Strilanc** [quantumlib/Cirq#1816]
Doctest finds lines like 

```
    >>> example(5)
    2
```

In docstrings and actually evaluates them and checks that they output what is shown in the example. This allows us to add an "Examples" section to docstrings while ensuring they function.

I did this recently, and _immediately_ made a failing example that I tried to submit. So perhaps we should verify this with actual test execution, in the same way that we verify code snippets found in the docs/ folder.

**Comment by Strilanc** [comment]
Example. In my PR https://github.com/quantumlib/Cirq/pull/1814

```
python -m doctest cirq/value/digits.py
```

Produced

```
**********************************************************************
File "cirq/value/digits.py", line 134, in digits.big_endian_int_to_digits
Failed example:
    big_endian_int_to_digits(11, digit_count=4, base=[2, 3, 4])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest digits.big_endian_int_to_digits[1]>", line 1, in <module>
        big_endian_int_to_digits(11, digit_count=4, base=[2, 3, 4])
      File "cirq/value/digits.py", line 184, in big_endian_int_to_digits
        raise ValueError('Inconsistent digit count. len(base) != digit_count')
    ValueError: Inconsistent digit count. len(base) != digit_count
**********************************************************************
File "cirq/value/digits.py", line 140, in digits.big_endian_int_to_digits
Failed example:
    big_endian_int_to_digits(11, base=[2, 3, 4])
Expected:
    [0, 1, 0, 2]
Got:
    [0, 2, 3]
**********************************************************************
File "cirq/value/digits.py", line 143, in digits.big_endian_int_to_digits
Failed example:
    big_endian_int_to_digits(18, bit_count=8)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest digits.big_endian_int_to_digits[4]>", line 1, in <module>
        big_endian_int_to_digits(18, bit_count=8)
    TypeError: big_endian_int_to_digits() got an unexpected keyword argument 'bit_count'
**********************************************************************
File "cirq/value/digits.py", line 146, in digits.big_endian_int_to_digits
Failed example:
    big_endian_int_to_digits(18, bit_count=4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest digits.big_endian_int_to_digits[5]>", line 1, in <module>
        big_endian_int_to_digits(18, bit_count=4)
    TypeError: big_endian_int_to_digits() got an unexpected keyword argument 'bit_count'
**********************************************************************
File "cirq/value/digits.py", line 149, in digits.big_endian_int_to_digits
Failed example:
    big_endian_int_to_digits(-3, bit_count=4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest digits.big_endian_int_to_digits[6]>", line 1, in <module>
        big_endian_int_to_digits(-3, bit_count=4)
    TypeError: big_endian_int_to_digits() got an unexpected keyword argument 'bit_count'
**********************************************************************
1 items had failures:
   5 of   7 in digits.big_endian_int_to_digits
***Test Failed*** 5 failures.
```
