### ISSUE TITLE
Delayed importer fails for certain importers

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/Cirq#2125]
The delayed import functionality fails in a certain importer that creates a zip for hermetic python packaging for Google.

Here is what fails.

Traceback (most recent call last):
...
 File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "/build/work/.../py/cirq/_import.py", line 105, in create_module
    return self.loader.create_module(spec)
AttributeError: '_elfzipimport.ElfZipImporter' object has no attribute 'create_module'

**Comment by cduck** [comment]
The `create_module` method on a Loader is allowed to be not implemented or return `None` to indicate the default behavior.  https://docs.python.org/3/library/importlib.html#importlib.abc.Loader

The fix should just be to check if the `create_module` method exists and return `None` otherwise.

**Comment by dstrain115** [comment]
Ok, I can give that a try.

**Comment by balopat** [comment]
@dstrain115 is this still an issue?

**Comment by dstrain115** [comment]
I think we managed to work around the issue by building the package differently.  I am okay closing it and then re-opening it if we run into it again.

**Comment by balopat** [comment]
Thanks, let's do that then!
