### ISSUE TITLE
Problems installing cirq and cirq-dev

### ISSUE THREAD

**Issue by jmbaker94** [quantumlib/Cirq#2347]
By installing both cirq and cirq-dev on accident and when trying to fix by uninstalling one of the versions in a python environment, it seems like pip may be installing both to the same location and uninstalling one leaves a broken version of cirq which can imported but not really. This seems like a usability problem. 

```bash
$conda create -n cirq_tests
$conda activate cirq_tests
$pip install cirq-dev
$python -c "import cirq; print(cirq.__version__)"
0.6.0.dev
$pip install cirq
$python -c "import cirq; print(cirq.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/cirq/__init__.py", line 41, in <module>
    from cirq.experiments import (
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/cirq/experiments/__init__.py", line 7, in <module>
    from cirq.experiments.qubit_characterizations import (
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/cirq/experiments/qubit_characterizations.py", line 7, in <module>
    from matplotlib import pyplot as plt
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "/Users/jonathan-baker/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

While trying to install a package dependent on cirq-dev I accidentally uninstalled just cirq and the following occurs:

```bash
$pip uninstall cirq
Successfully uninstalled cirq-0.5.0
$python -c "import cirq; print(cirq.__version__)"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cirq' has no attribute '__version__'
```

This similarly happens if I have installed both and uninstall cirq-dev:
```bash
$pip uninstall cirq-dev
Successfully uninstalled cirq-dev-0.6.0.dev20191014205508
$python -c "import cirq; print(cirq.__version__)"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cirq' has no attribute '__version__'
```

**Comment by Strilanc** [comment]
I'm not sure if this is worth fixing. I'd rather this problem than adding thousands of dev versions to the `cirq` pypi package.

Does the same issue happen with `tensorflow` vs `tf-nightly`? Maybe there's a trick to it.

**Comment by dabacon** [comment]
I'm currently unable to reproduce this using either conda or using a virtualenv.   

I'm going to close as this is a sort of strange corner case where the unstable and stable version are co-installed.  

My only thought is that there could be someway to warn if you are about to do this.
