### ISSUE TITLE
cirq.google.Engine warns about api client discovery_cache

### ISSUE THREAD

**Issue by maffoo** [quantumlib/Cirq#251]
I get the following warnings when calling `Engine.run`:
```
WARNING: Logging before flag parsing goes to stderr.
W0330 09:41:57.640754 139916366640896 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/usr/local/google/home/maffoo/.virtualenvs/cirq/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/maffoo/.virtualenvs/cirq/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/maffoo/.virtualenvs/cirq/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/maffoo/.virtualenvs/cirq/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/google/home/maffoo/.virtualenvs/cirq/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```
Relevant output from `pip freeze`:
```
...
google-api-python-client==1.6.5
google-auth==1.4.1
google-auth-httplib2==0.0.3
...
oauth2client==4.1.2
...
```

**Comment by vtomole** [comment]
This may be solved by an in memory cache. https://github.com/googleapis/google-api-python-client/issues/325#issuecomment-274349841

Can someone with Engine access try it out? 

CC: @dabacon @dstrain115  @viathor

**Comment by dabacon** [comment]
I don't see this.  Think the way we are accessing engine now won't hit this.  Going to close unless someone can reproduce.
