### ISSUE TITLE
aqt module import

### ISSUE THREAD

**Issue by alexandrupaler** [quantumlib/Cirq#2746]
without explicitly doing `from cirq.aqt import AQTSampler` although` import cirq` was done, the code line below raises `AttributeError: module 'cirq' has no attribute 'aqt'`

```
 aqt_sampler = cirq.aqt.AQTSampler(
        remote_host="rmeote",
        access_token="mykey"
    )
```

**Comment by mpharrigan** [comment]
FYI this is pretty standard python behavior

```
In[10]: import scipy
In[11]: scipy.linalg.expm()
Traceback (most recent call last):
  File "/usr/local/google/home/mpharrigan/cirq/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-d534fa3c30db>", line 1, in <module>
    scipy.linalg.expm()
AttributeError: module 'scipy' has no attribute 'linalg'
In[12]: import scipy.linalg
In[13]: scipy.linalg.expm()
Traceback (most recent call last):
  File "/usr/local/google/home/mpharrigan/cirq/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-d534fa3c30db>", line 1, in <module>
    scipy.linalg.expm()
TypeError: expm() missing 1 required positional argument: 'A'
```

**Comment by alexandrupaler** [comment]
Thank you. Did not know. Nevertheless, I find it annoying.

**Comment by mpharrigan** [comment]
Yes, in Cirq we import everything, so I think #2748 is the correct change! 

I think scipy doesn't do it to keep import times low

**Comment by vtomole** [comment]
This is not an issue anymore due to the recently adopted packaging strategy.
```python
>>> import cirq_aqt
>>> cirq_aqt.AQTSampler(remote_host="remote", access_token="mykey")
<cirq_aqt.aqt_sampler.AQTSampler object at 0x7fb613b97280>
```
