### ISSUE TITLE
Doctest failure on macOS

### ISSUE THREAD

**Issue by cduck** [quantumlib/Cirq#2925]
The failure appears to be caused by one test creating a 3D pyplot figure and another test assuming the default current figure is 2D.  My guess is that the tests are run in a different order on macOS.

One fix is to add the following code that clears the current figure to the example code in [contrib/routing/device.py#L62](https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/routing/device.py#L62):
```python
>>> import matplotlib.pyplot as plt
>>> plt.clf()
```

Failure:
```
cirq/contrib/routing/device.py
1 failed, 4 passed, 5 total
**********************************************************************
File "cirq/contrib/routing/device.py", line 64, in device.nx_qubit_layout
Failed example:
    nx.draw_networkx(g, pos=pos)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/doctest.py", line 1329, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest device.nx_qubit_layout[4]>", line 1, in <module>
        nx.draw_networkx(g, pos=pos)
      File "/usr/local/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 277, in draw_networkx
        draw_networkx_labels(G, pos, **kwds)
      File "/usr/local/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 803, in draw_networkx_labels
        t = ax.text(x, y,
    TypeError: text() missing 1 required positional argument: 's'
```
(`Axes.text(x, y, s, ...)` but `Axes3D.text(x, y, z, s, ...)`)

**Comment by 95-martin-orion** [comment]
Is there a PR out for this? It looks like a lot of PRs are blocked on it...

**Comment by cduck** [comment]
I don't have time to make a PR.  Feel free to make my suggested change.  If are other examples that use matplotlib, they should probably also be fixed.

I'm not sure the best way to prevent the test order from affecting other tests in the future.
