### ISSUE TITLE
Doctest failing on Github actions

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#2985]
```

Run check/doctest -q
cirq/contrib/routing/device.py
1 failed, 4 passed, 5 total
**********************************************************************
File "cirq/contrib/routing/device.py", line 64, in cirq_doctest_module.nx_qubit_layout
Failed example:
    nx.draw_networkx(g, pos=pos)
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest cirq_doctest_module.nx_qubit_layout[4]>", line 1, in <module>
        nx.draw_networkx(g, pos=pos)
      File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 277, in draw_networkx
        draw_networkx_labels(G, pos, **kwds)
      File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 814, in draw_networkx_labels
        clip_on=True,
    TypeError: text() missing 1 required positional argument: 's'

Failed: 1 failed, 88 passed, 89 total
##[error]Process completed with exit code 1.
```

**Comment by cduck** [comment]
Related to #2925.

**Comment by vtomole** [comment]
Fixed by https://github.com/quantumlib/Cirq/pull/2987
