### ISSUE TITLE
It's too hard to run a noisy circuit correctly

### ISSUE THREAD

**Issue by olsonjonny** [quantumlib/Cirq#343]
I’m trying to apply the noise simulator to a circuit, but I run into this:

```
root@ce2cd89416a5:~/google_autoencoder/src/qae# python3 qae_noisy.py
Traceback (most recent call last):
  File "qae_noisy.py", line 170, in <module>
    run_sim(a,b,x,z,0.5,100,True,True,True)
  File "qae_noisy.py", line 136, in run_sim
    result = simulator.run(circuit_run, qubits = qub)
  File "/usr/local/lib/python3.5/dist-packages/cirq-0.1-py3.5.egg/cirq/google/sim/xmon_simulator.py", line 145, in run
    qubits, initial_state)[0]
  File "/usr/local/lib/python3.5/dist-packages/cirq-0.1-py3.5.egg/cirq/google/sim/xmon_simulator.py", line 192, in run_sweep
    all_step_results)
  File "/usr/local/lib/python3.5/dist-packages/cirq-0.1-py3.5.egg/cirq/google/sim/xmon_simulator.py", line 311, in simulator_iterator
    gate.half_turns)
  File "/usr/local/lib/python3.5/dist-packages/cirq-0.1-py3.5.egg/cirq/study/resolver.py", line 57, in value_of
    return self.param_dict[value.name]
KeyError: 'error_parameter0'
```
 
The implementation of the noisy simulator is done in these lines in the code I’m running:

```python
def noisy_job(a,b,x,z,alpha,exact=False):
    job = Job(test_circuit(a,b,x,z,alpha,True))
    noisy = DepolarizerChannel(probability=0.1)
    noisy_job = noisy.transform_job(job)
    return noisy_job.circuit
```
 
Notably, I do not seem to run into the error when I remove “probability=0.1”---however, I also don’t seem to be observing any error applied to the output state either.

**Comment by dabacon** [comment]
We are proposing #929 as the path forward for our first version of noisy simulators.

**Comment by Strilanc** [comment]
Obsoleted by all the other noisy simulator issues and work.
