### ISSUE TITLE
Installing dev tools gives error building qiskit-aer

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#3766]
**Description of the issue**
Installing dev tools gives error building qiskit-aer

**How to reproduce the issue**
In a fresh virtual environment, execute
```
pip install -r dev_tools/conf/pip-list-dev-tools.txt
```
Result:
```
...
  CMake Error at .eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find Cython (missing: CYTHON_EXECUTABLE)
  Call Stack (most recent call first):
    .eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /home/kjs/environments/cirq/lib/python3.9/site-packages/skbuild/resources/cmake/FindCython.cmake:73 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    cmake/cython_utils.cmake:2 (find_package)
    qiskit/providers/aer/pulse/qutip_extra_lite/cy/CMakeLists.txt:2 (include)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/home/kjs/environments/cirq/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 582, in setup
      env = cmkr.configure(cmake_args,
    File "/home/kjs/environments/cirq/lib/python3.9/site-packages/skbuild/cmaker.py", line 229, in configure
      raise SKBuildError(
  
  An error occurred while configuring with CMake.
    Command:
      /tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4/.eggs/cmake-3.18.4.post1-py3.9-linux-x86_64.egg/cmake/data/bin/cmake /tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/kjs/environments/cirq/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.1 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.9.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/home/kjs/environments/cirq/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4
    Working directory:
      /tmp/pip-install-1wlhsc3q/qiskit-aer_353b8531be2847d8914b5803ea1264b4/_skbuild/linux-x86_64-3.9/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for qiskit-aer
...
```

**Cirq version**
f08b3444004e44b6c0cebf0ad4136775f8decdf9

**Comment by balopat** [comment]
Thanks, @kevinsung - I'm guessing this is a python3.9 issue - we haven't got around to do the upgrade yet, but we should.

**Comment by kevinsung** [comment]
I can't reproduce it anymore, so I'll close.
