### ISSUE TITLE
Add support for parameteric custom gates

### ISSUE THREAD

**Issue by jlbosse** [quantumlib/Cirq#3778]
**Is your feature request related to a use case or problem? Please describe.**
As of now it is not possible to create custom gates as described [here](https://quantumai.google/cirq/custom_gates) that can be 
parametrized with a `sympy.Symbol` as described for example for [QAOA](https://quantumai.google/cirq/tutorials/educators/qaoa_ising).

To me this feature would be really useful for any application of VQE, since most of the time I don't think in terms of 
parameterizing Rz or Rx gates, but in terms of paremeterizing bigger blocks / layers.

**Describe the solution you'd like**
Here is the code that would like to work:

```python
from cirq import *
import sympy as smp

class MyGate(TwoQubitGate):
    def __init__(self, theta):
        super(MyGate, self)
        self.theta = theta
        
    def _decompose_(self, qubits):
        q0, q1 = qubits
        yield Z(q0)**(self.theta)
        yield Z(q1)**(self.theta)
        yield CNOT(q0, q1)
        yield Z(q1)**(self.theta)
        yield CNOT(q0, q1)

    # This works even less because numpy can't handle Sympy symbols
    # def _unitary_(self):
    #    return np.array([[np.exp(-1j*self.theta), 0, 0, 0],
    #                     [0, np.exp(1j*self.theta) * np.cos(2*self.theta), -1j*np.exp(1j*self.theta)*np.sin(2*self.theta), 0],
    #                     [0, -1j*np.exp(1j*self.theta) * np.sin(2*self.theta), np.exp(1j*self.theta)*np.cos(2*self.theta), 0],
    #                     [0, 0, 0, np.exp(-1j*self.theta)]])
    
    def _circuit_diagram_info_(self, args):
        return f"My({self.theta})", "My"

if __name__ == "__main__":
    q0, q1 = LineQubit(0), LineQubit(1)
    sim = Simulator()
    circuit = Circuit()
    a = smp.Symbol("a")
    circuit.append(MyGate(a)(q0, q1))

    # Functionally equivalent circuit that actually runs
    #circuit.append(Z(q0)**(a))
    #circuit.append(Z(q1)**(a))
    #circuit.append(CNOT(q0, q1))
    #circuit.append(Z(q1)**(a))
    #circuit.append(CNOT(q0, q1))

    param_resolver = ParamResolver({"a": 1.0})
    wf = sim.simulate(circuit, param_resolver=param_resolver).final_state_vector
    print(wf)
```

which prints 

```
Traceback (most recent call last):
  File "/home/janlukas/klo/cirq-parametric-gate.py", line 42, in <module>
    wf = sim.simulate(circuit, param_resolver=param_resolver).final_state_vector
  File "/usr/lib/python3.9/site-packages/cirq/sim/simulator.py", line 213, in simulate
    return self.simulate_sweep(
  File "/usr/lib/python3.9/site-packages/cirq/sim/simulator.py", line 297, in simulate_sweep
    for step_result in all_step_results:
  File "/usr/lib/python3.9/site-packages/cirq/sim/sparse_simulator.py", line 247, in _base_iterator
    protocols.act_on(op, sim_state)
  File "/usr/lib/python3.9/site-packages/cirq/protocols/act_on_protocol.py", line 108, in act_on
    result = arg_fallback(action, allow_decompose=allow_decompose)
  File "/usr/lib/python3.9/site-packages/cirq/sim/act_on_state_vector_args.py", line 159, in _act_on_fallback_
    result = strat(action, self)
  File "/usr/lib/python3.9/site-packages/cirq/sim/act_on_state_vector_args.py", line 195, in _strat_act_on_state_vector_from_apply_decompose
    return _act_all_on_state_vector(operations, qubits, args)
  File "/usr/lib/python3.9/site-packages/cirq/sim/act_on_state_vector_args.py", line 208, in _act_all_on_state_vector
    protocols.act_on(action, args)
  File "/usr/lib/python3.9/site-packages/cirq/protocols/act_on_protocol.py", line 116, in act_on
    raise TypeError("Failed to act action on state argument.\n"
TypeError: Failed to act action on state argument.
Tried both action._act_on_ and args._act_on_fallback_.

State argument type: <class 'cirq.sim.act_on_state_vector_args.ActOnStateVectorArgs'>
Action type: <class 'cirq.ops.gate_operation.GateOperation'>
Action repr: (cirq.Z**sympy.Symbol('a')).on(cirq.LineQubit(0))
```
instead of the final wavefunction.

**[optional] Describe alternatives/workarounds you've considered**
My current workaround is adding the whole decomposition of my layers manually, like so:

```python
def add_mygate(circuit, q0, q1, theta):
    #circuit.append(Z(q0)**(theta))
    #circuit.append(Z(q1)**(theta))
    #circuit.append(CNOT(q0, q1))
    #circuit.append(Z(q1)**(theta))
    #circuit.append(CNOT(q0, q1))
...

# build the circuit
add_mygate(circuit, q0, q1, theta) # instead of circuit.append(MyGate(theta)(q0, q1))
# and more circuit building
```
This works as expected, but has the drawback that printing the circuit gets much more cluttered and it feels less elegant.

**What is the urgency from your perspective for this issue? Is it blocking important work?**

P1 - I need this no later than the next release (end of quarter)

**Comment by balopat** [comment]
Thank you for opening the issue and explaining your use case! 

For parameters to work, you have to add [`resolve_parameters` protocol](https://quantumai.google/reference/python/cirq/protocols/resolve_parameters) to the gate:

```
class MyGate(TwoQubitGate):
    def __init__(self, theta):
        super(MyGate, self)
        self.theta = theta

    def _decompose_(self, qubits):
        q0, q1 = qubits
        yield Z(q0) ** (self.theta)
        yield Z(q1) ** (self.theta)
        yield CNOT(q0, q1)
        yield Z(q1) ** (self.theta)
        yield CNOT(q0, q1)

    def _resolve_parameters_(self, param_resolver: 'cirq.ParamResolver', recursive: bool):
        return MyGate(cirq.resolve_parameters(self.theta, param_resolver, recursive=recursive))

    def _circuit_diagram_info_(self, args):
        return f"My({self.theta})", "My"
```

Should do the trick. 

=============

If you are willing to try it, we are introducing a new concept to handle subcircuits: `CircuitOperation` - this will have a more structure and will allow for nesting circuits and looping (via the `repetitions` parameter). 

```
def my_op(theta):
    q0, q1 = cirq.LineQubit.range(2)
    return CircuitOperation(FrozenCircuit([
        Z(q0) ** (theta),
        Z(q1) ** (theta),
        CNOT(q0, q1),
        Z(q1) ** (theta),
        CNOT(q0, q1),
        ]))

if __name__ == "__main__":
    q0, q1 = LineQubit(0), LineQubit(1)
    sim = Simulator()
    circuit = Circuit()
    a = smp.Symbol("a")
    circuit.append(my_op(a).with_qubits(q0, q1))

    param_resolver = ParamResolver({"a": 1.0})
    print(circuit)
    circuit = cirq.resolve_parameters(circuit, param_resolver, recursive=False)
    wf = sim.simulate(circuit).final_state_vector
    print(wf)
```
which prints: 

```
      Circuit_0x40258af8fe372b4c:
0: ───[ 0: ───Z^a───@─────────@─── ]───
      [             │         │    ]
      [ 1: ───Z^a───X───Z^a───X─── ]
      │
1: ───#2───────────────────────────────
[1.+0.j 0.-0.j 0.-0.j 0.-0.j]
```

**Comment by jlbosse** [comment]
Thank you for the hint to the [`parameter_resolve`](https://quantumai.google/reference/python/cirq/protocols/resolve_parameters) protocol. Since my desired functionality is indeed there and I just didn't find it, it seems to be more a documentation Issue. 

If you want, I can add a paragraph to the "With parameters" section in [`docs/custom_gates.ipynb`](https://github.com/quantumlib/Cirq/blob/master/docs/custom_gates.ipynb) and open a PR about it.

**Comment by jlbosse** [comment]
Thank you for the hint to the [`parameter_resolve`](https://quantumai.google/reference/python/cirq/protocols/resolve_parameters) protocol. Since my desired functionality is indeed there and I just didn't find it, it seems to be more a documentation Issue. 

If you want, I can add a paragraph to the "With parameters" section in [`docs/custom_gates.ipynb`](https://github.com/quantumlib/Cirq/blob/master/docs/custom_gates.ipynb) and open a PR about it.
