### ISSUE TITLE
GateOpSerializer in cirq.google does not accept numpy numeric types as convertible to float

### ISSUE THREAD

**Issue by wjhuggins** [quantumlib/Cirq#4010]
**Description of the issue**

GateOpSerializer in cirq.google does not accept numpy numeric types as convertible to float. It's easy for a numpy.int64 types (for example) to end up getting fed in here.

**How to reproduce the issue**

Trying to serialize a gate that would lead to a numpy.int64 being passed to this helper method should do it.

```
    def _check_type(self, value: arg_func_langs.ARG_LIKE, arg: SerializingArg) -> None:
        if arg.serialized_type == float:
            if not isinstance(value, (float, int)):
                raise ValueError(f'Expected type convertible to float but was {type(value)}')
        elif arg.serialized_type == List[bool]:
            if not isinstance(value, (list, tuple, np.ndarray)) or not all(
                isinstance(x, (bool, np.bool_)) for x in value
            ):
                raise ValueError(f'Expected type List[bool] but was {type(value)}')
        elif value is not None and not isinstance(value, arg.serialized_type):
            raise ValueError(
                'Argument {} had type {} but gate returned type {}'.format(
                    arg.serialized_name, arg.serialized_type, type(value)
                )
            )
```

<details>

```
Traceback (most recent call last):
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/google/home/whuggins/Projects/qc/newtilities.py", line 99, in run
    data = build_experiment(params, dependencies)
  File "/usr/local/google/home/whuggins/Projects/qc/experiment.py", line 93, in build_experiment
    raw_samples = get_samples_from_experiment(blueprint.compiled_circuit,
  File "/usr/local/google/home/whuggins/Projects/qc/quantum_engine_utilities.py", line 51, in get_samples_from_experiment
    job = engine.run_batch(
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/engine/engine.py", line 365, in run_batch
    engine_program = self.create_batch_program(
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/engine/engine.py", line 525, in create_batch_program
    gate_set.serialize(program, msg=batch.programs.add())
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/serializable_gate_set.py", line 125, in serialize
    self._serialize_circuit(
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/serializable_gate_set.py", line 253, in _serialize_circuit
    self.serialize_op(
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/serializable_gate_set.py", line 165, in serialize_op
    proto_msg = serializer.to_proto(
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/op_serializer.py", line 137, in to_proto
    value = self._value_from_gate(op, arg)
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/op_serializer.py", line 184, in _value_from_gate
    self._check_type(value, arg)
  File "/usr/local/google/home/whuggins/Projects/qc/env/lib/python3.9/site-packages/cirq/google/op_serializer.py", line 191, in _check_type
    raise ValueError(f'Expected type convertible to float but was {type(value)}')
ValueError: Expected type convertible to float but was <class 'numpy.int64'>
```

</details>

**Cirq version**
0.11.0.dev

**Comment by balopat** [comment]
This should be trivial to fix by adding np.integer into the `isinstance` check: `if not isinstance(value, (float, int, np.integer)):` + we'll need a test. Great first issue for someone.

**Comment by joaomvbasso** [comment]
Hi, I'd like to tackle this issue.

**Comment by balopat** [comment]
It's all yours, thanks for signing up!

**Comment by 95-martin-orion** [comment]
@dstrain115 it looks like a solution has been waiting for some time - can we merge it or close this?

Marking pre-1.0 in lieu of a decision here.

**Comment by dstrain115** [comment]
GateOpSerializer is deprecated.  Assigning myself to check if this is implemented in the new CircuitSerializer and just give an update on it.
