### ISSUE TITLE
JSON serialization panics when given numpy values

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Cirq#4030]
```python
print(cirq.to_json({'value': 1}))
{
  "value": 1
}
print(cirq.to_json({'value': np.array(1)}))
Traceback (most recent call last):
  File "/usr/local/google/home/mpharrigan/cirq/env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-0e5a100f1b72>", line 1, in <module>
    print(cirq.to_json({'value': np.array(1)}))
  File "/usr/local/google/home/mpharrigan/cirq/cirq/cirq/protocols/json_serialization.py", line 515, in to_json
    if has_serializable_by_keys(obj):
  File "/usr/local/google/home/mpharrigan/cirq/cirq/cirq/protocols/json_serialization.py", line 445, in has_serializable_by_keys
    return any(has_serializable_by_keys(elem) for pair in obj.items() for elem in pair)
  File "/usr/local/google/home/mpharrigan/cirq/cirq/cirq/protocols/json_serialization.py", line 445, in <genexpr>
    return any(has_serializable_by_keys(elem) for pair in obj.items() for elem in pair)
  File "/usr/local/google/home/mpharrigan/cirq/cirq/cirq/protocols/json_serialization.py", line 447, in has_serializable_by_keys
    return any(has_serializable_by_keys(elem) for elem in obj)
TypeError: iteration over a 0-d array
```

This used to work. The above is a minimal example taken from real code that used to work with previous cirq versions.

**Comment by mpharrigan** [comment]
```diff
diff --git a/cirq/protocols/json_serialization.py b/cirq/protocols/json_serialization.py
index 77bc8d8e..b1dcdd67 100644
--- a/cirq/protocols/json_serialization.py
+++ b/cirq/protocols/json_serialization.py
@@ -444,6 +444,8 @@ def has_serializable_by_keys(obj: Any) -> bool:
     if isinstance(obj, Dict):
         return any(has_serializable_by_keys(elem) for pair in obj.items() for elem in pair)
     if hasattr(obj, '__iter__') and not isinstance(obj, str):
+        if isinstance(obj, np.ndarray) and obj.ndim==0:
+            return False
         return any(has_serializable_by_keys(elem) for elem in obj)
     return False
```

is my hack. I don't know what the "true" fix would be.

**Comment by balopat** [comment]
I have no better idea than your fix either. If feel like this is a highly special case where numpy is kind of breaking the iterable contract by having `__iter__` on a class which can be initialized to be non-iterable...
I say let's special case it to np.ndarray, ndim==0. Alternatively we could catch TypeError, but I prefer the explicit special logic!

**Comment by mpharrigan** [comment]
We could [EAFP](https://docs.python.org/3/glossary.html#term-eafp) and try/catch Type error around the any()

**Comment by 95-martin-orion** [comment]
I have mixed feelings about using EAFP (it could lead to hard-to-find performance hits, depending on implementation), but overall agree with the proposed solution. The intent of this code is to locate key-serializable objects (like `FrozenCircuit`) in iterables; anything that would never contain such an object can be skipped.
