### ISSUE TITLE
Ugly exception warning when only cirq-core is installed

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4106]
**Description of the issue**

We produce an ugly warning that cirq_google is missing if the user only installs cirq-core.

**How to reproduce the issue**

1. Create an empty virtual env.
2. `pip install cirq-core`
3. `python -c 'import cirq'`

<details>

```
>>> import cirq
--- Logging error ---
Traceback (most recent call last):
  File "/Users/balintp/.virtualenvs/tempenv-4e8e54466376/lib/python3.8/site-packages/cirq/__init__.py", line 576, in <module>
    _compat.deprecated_submodule(
  File "/Users/balintp/.virtualenvs/tempenv-4e8e54466376/lib/python3.8/site-packages/cirq/_compat.py", line 546, in deprecated_submodule
    new_module = importlib.import_module(new_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cirq_google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/balintp/.virtualenvs/tempenv-4e8e54466376/lib/python3.8/site-packages/cirq/__init__.py", line 585, in <module>
    warning("Can't import cirq.google: ", ex)
Message: "Can't import cirq.google: "
Arguments: (ModuleNotFoundError("No module named 'cirq_google'"),)
```

</details>

**Cirq version**
v0.11

**Comment by mpharrigan** [comment]
This is now a problem with aqt and ionq

**Comment by mpharrigan** [comment]
Ideas:

1) Don't print the full exception, which is long and says its an Error when it's actually a warning. I was legitimately surprised to see that `import cirq` had actually succeeded since I saw so many exceptions in red text

2) Upon import error, define the subpackages to a shim class that will throw a meaningful exception when you try to use it

```python
try:
  deprecated_submodule(cirq_google)
except ImportError:
  sys.modules['cirq.google'] = ValueError("Not installed")
```

**Comment by balopat** [comment]
1. I created a better error message - it does print the whole exception though for prosperity, otherwise we won't surface the true error.  
2. I followed this idea of "deferred/lazy error throwing" though I was skeptical first, and came up with #4324 - I think it works out pretty well in the end.
