### ISSUE TITLE
Flake in json_serialization_test

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4145]
Potential flake that I've seen once in CI as well as (I think) once on my mac locally:

```
Comparing against revision 'origin/master'.
Found 3 test files associated with changes.
============================= test session starts ==============================
platform linux -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/runner/work/Cirq/Cirq
plugins: asyncio-0.15.1, cov-2.12.0, forked-1.3.0, xdist-2.2.1
collected 55 items / 1 error / 54 selected

==================================== ERRORS ====================================
_____ ERROR collecting cirq-core/cirq/protocols/json_serialization_test.py _____
cirq-core/cirq/protocols/json_serialization_test.py:429: in <module>
    _list_public_classes_for_tested_modules(),
cirq-core/cirq/protocols/json_serialization_test.py:422: in _list_public_classes_for_tested_modules
    for mod_spec in MODULE_TEST_SPECS
/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/contextlib.py:119: in __exit__
    next(self.gen)
cirq-core/cirq/testing/deprecation.py:66: in assert_deprecated
    yield True
cirq-core/cirq/testing/logs.py:98: in __exit__
    f'Expected {count} log message but ' f'got {len(records)}. Log messages: ' f'{msgs}'
E   AssertionError: Expected 1 log message but got 0. Log messages: []
=========================== short test summary info ============================
ERROR cirq-core/cirq/protocols/json_serialization_test.py - AssertionError: E...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.48s ===============================
```

**Comment by balopat** [comment]
It wasn't a flake. 
Adding some info in case someone runs into something similar. 

What was happening is that the cirq-google dependencies were missing on the CI job due to my refactors. 
This triggered the conditional import of `cirq_google` package to fail. 
The json_serialization_test.py file checks for `cirq_google` being present on the PYTHONPATH - and then it assumes that it is included - and asserts the deprecationwarning to be emitted. But, because of the missing dependencies, `import google` in the protobuf files fail, leading to an import error in `cirq/__init__.py` which caught by a way too wide Exception handling mechanism (https://github.com/quantumlib/Cirq/issues/4106 should fix this and result in a better error message)...resulting in an inconsistent state: `cirq_google` is on the path but `cirq.google` does not exist. 

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-core/cirq/__init__.py", line 581, in <module>
    _compat.deprecated_submodule(
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-core/cirq/_compat.py", line 546, in deprecated_submodule
    new_module = importlib.import_module(new_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-google/cirq_google/__init__.py", line 17, in <module>
    from cirq_google import api
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-google/cirq_google/api/__init__.py", line 16, in <module>
    from cirq_google.api import v2
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-google/cirq_google/api/v2/__init__.py", line 16, in <module>
    from cirq_google.api.v2 import (
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-google/cirq_google/api/v2/batch_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1070, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 500, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 508, in _try_load_conftest
    self._getconftestmodules(anchor, importmode)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 536, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/config/__init__.py", line 570, in _importconftest
    mod = import_path(conftestpath, mode=importmode)
  File "/usr/local/google/home/balintp/.virtualenvs/tmp-e19c4b6b0f10298/lib/python3.8/site-packages/_pytest/pathlib.py", line 524, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/google/home/balintp/dev/proj/Cirq/cirq-core/cirq/__init__.py", line 590, in <module>
    warning("Can't import cirq.google: ", ex)
Message: "Can't import cirq.google: "
Arguments: (ModuleNotFoundError("No module named 'google'"),)
_________________________________________________________________________________________________________________________ ERROR collecting cirq-core/cirq/protocols/json_serialization_test.py _________________________________________________________________________________________________________________________
cirq-core/cirq/protocols/json_serialization_test.py:429: in <module>
    ???
cirq-core/cirq/protocols/json_serialization_test.py:420: in _list_public_classes_for_tested_modules
    return [
/usr/local/lib/python3.8/contextlib.py:120: in __exit__
    next(self.gen)
cirq-core/cirq/testing/deprecation.py:66: in assert_deprecated
    yield True
cirq-core/cirq/testing/logs.py:97: in __exit__
    assert count is None or len(records) == count, (
E   AssertionError: Expected 1 log message but got 0. Log messages: []
--------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout ----------------------------------------------------------------------------------------------------------------------------------------------------
cirq_google on path : True
=============================================================================================================================================== short test summary info ================================================================================================================================================
ERROR cirq-core/cirq/protocols/json_serialization_test.py - AssertionError: Expected 1 log message but got 0. Log messages: []

```
