### ISSUE TITLE
Resolve proto DeprecationWarnings

### ISSUE THREAD

**Issue by balopat** [quantumlib/Cirq#4161]
**Description of the issue**

On certain environments (e.g. Windows 3.8 builds in CI and @dstrain115  reported seeing these on Linux python 3.9) check/pytest results in a ton of DeprecationWarnings related to pb2 files. We should resolve these. 

<details>

```
cirq-google\cirq_google\api\v2\program_pb2.py:18
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:18: DeprecationWarning: Call to deprecated create function FileDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    DESCRIPTOR = _descriptor.FileDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:34
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:34: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:38
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:38: DeprecationWarning: Call to deprecated create function EnumValueDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.EnumValueDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:28
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:28: DeprecationWarning: Call to deprecated create function EnumDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _CIRCUIT_SCHEDULINGSTRATEGY = _descriptor.EnumDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:58
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:58: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:65
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:65: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:72
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:72: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:79
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:79: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:97
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:97: DeprecationWarning: Call to deprecated create function OneofDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.OneofDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:51
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:51: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _PROGRAM = _descriptor.Descriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:113
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:113: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:120
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:120: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:138
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:138: DeprecationWarning: Call to deprecated create function OneofDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.OneofDescriptor(

cirq-google\cirq_google\api\v2\program_pb2.py:106
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\program_pb2.py:106: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    DESCRIPTOR = _descriptor.FileDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:38
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:38: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:31
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:31: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _RESULT = _descriptor.Descriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:69
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:69: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:76
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:76: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:62
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:62: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _SWEEPRESULT = _descriptor.Descriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:107
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:107: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:114
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:114: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:100
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:100: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _PARAMETERIZEDRESULT = _descriptor.Descriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:145
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:145: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:152
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:152: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

cirq-google\cirq_google\api\v2\result_pb2.py:138
  D:\a\Cirq\Cirq\cirq-google\cirq_google\api\v2\result_pb2.py:138: DeprecationWarning: Call to deprecated create function Descriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _MEASUREMENTRESULT = _descriptor.Descriptor(

```

</details>

**Comment by balopat** [comment]
Upgrading grpcio-tools is not really an option otherwise we'll break Tensorflow Quantum. 
The following error is thrown if we compile the pb2 files with gprcio-tools==1.38: 


```
Traceback (most recent call last):
  File "/usr/local/google/home/balintp/.cache/bazel/_bazel_balintp/2a5372a3daafe520558a60f08ef39302/execroot/__main__/bazel-out/k8-opt/bin/tensorflow_quantum/python/differentiators/linear_combination_test.runfiles/__main__/tensorflow_quantum/python/differentiators/linear_combination_test.py", line 20, in <module>
    import cirq
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq/__init__.py", line 585, in <module>
    _compat.deprecated_submodule(
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq/_compat.py", line 546, in deprecated_submodule
    new_module = importlib.import_module(new_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq_google/__init__.py", line 17, in <module>
    from cirq_google import api
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq_google/api/__init__.py", line 16, in <module>
    from cirq_google.api import v2
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq_google/api/v2/__init__.py", line 16, in <module>
    from cirq_google.api.v2 import (
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq_google/api/v2/batch_pb2.py", line 14, in <module>
    from . import program_pb2 as cirq__google_dot_api_dot_v2_dot_program__pb2
  File "/usr/local/google/home/balintp/.virtualenvs/tf38/lib/python3.8/site-packages/cirq_google/api/v2/program_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

```

This is because TFQ uses protobuf 3.9.12 - which is a hard dependency on their Tensorflow version 2.4.1 as far as I understand.

**Comment by balopat** [comment]
Oh the way to repro this, if someone's up for it: 

Use a linux machine! 

1. build TFQ from source (https://www.tensorflow.org/quantum/install) - so now you have a virtual env e.g. called `tfq38` where `scripts/test_all.sh` succeeds. 
2. in a separate directory, get latest Cirq from master, use a separate virtualenv, e.g. `cirq38` (just for prosperity's sake) and bump `grpcio-tools>1.26.0` in `dev_tools/requirements/deps/protos.txt`, then run `pip install -U -r dev_tools/requirements/dev.env.txt` - this should install `grpcio-tools==1.38.0` in your `cirq38` env. 
3. run `dev_tools/build-protos.sh` - this should generate the new pb2 files. `git status` should show them changed! 
```
        modified:   cirq-google/cirq_google/api/v1/operations_pb2.py
        modified:   cirq-google/cirq_google/api/v1/params_pb2.py
        modified:   cirq-google/cirq_google/api/v1/program_pb2.py
        modified:   cirq-google/cirq_google/api/v2/batch_pb2.py
        modified:   cirq-google/cirq_google/api/v2/calibration_pb2.py
        modified:   cirq-google/cirq_google/api/v2/device_pb2.py
        modified:   cirq-google/cirq_google/api/v2/metrics_pb2.py
        modified:   cirq-google/cirq_google/api/v2/program_pb2.py
        modified:   cirq-google/cirq_google/api/v2/result_pb2.py
        modified:   cirq-google/cirq_google/api/v2/run_context_pb2.py
        modified:   dev_tools/requirements/deps/protos.txt
```
Specifically we are looking for these changes:
![image](https://user-images.githubusercontent.com/635073/120864555-3f458980-c541-11eb-8b2f-3c4d2db5df5f.png)

As protobuf throws a DeprecationWarning if the pb2 does not use the  `_internal_create_key` method: https://github.com/protocolbuffers/protobuf/blob/a1d8f8f96900468f09ced2ce9d23dea5a1bc070c/python/google/protobuf/descriptor.py#L328-L329

4. Now in your Cirq directory, switch to the `tfq38` virtualenv and run `pip install . ./cirq-core ./cirq-google`
5. Go back to your TFQ dir, `blaze clean --expunge` and run the `scripts/test_all.sh` again - you should see the above failure.

**Comment by MichaelBroughton** [comment]
@balopat Wow nice! This was the original source of the error we found over in TFQ. 

Here's why I **think** it's happening: Here's the original piper sync that brought in the `_internal_create_key` entry: https://github.com/protocolbuffers/protobuf/commit/b99994d994e399174fe688a5efbcb6d91f36952a#diff-36475d83594de2ba8efd80eb6c5c276cce4f5553871d53a433d03d2f503088a8 which was present in protobuf >= 3.12.0-rc1

My guess is that these pb2 files were compiled using a protoc release older than 3.12.0-rc1 (maybe 3.9.2). This is currently an ongoing issue in TensorFlow to update proto dependencies everywhere: https://github.com/tensorflow/tensorflow/commit/bd3e005eb9c8d23992d793d54b28e103e2348866 . Currently what they are doing is rolling with 3.9.2 protobuf and protoc (https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/workspace2.bzl#L564) with some patchwork that get's them up somewhere around 3.11 and 3.12 (with 3.14 not working on platforms other than just windows) support.

So, In order to get rid of this error I believe that Cirq needs to re-generate these pb2 files with a newer protoc, maybe for sanity sake we try 3.12.0 on the nose to maximize compatibility chances ? `protoc --version`
 
TFQ inherits all of these troubles from TF by depending on TF and protoc on both C++ and python levels, we also don't precompile our pb2 files and include them in the repo and instead opt to build them each time like how one might do with bazel/blaze.  Here are some dependencies we also inherit on the python side that might prove troubling:
```
grpcio ~= 1.34.0  # inherited from tf.
numpy ~= 1.19.2  # tf can detect being compiled against other numpy versions and breaks
protobuf >= 3.9.2   # as you can see in the links above it does still break around 3.14 on windows and so this isn't perfect.
```

**Comment by balopat** [comment]
The first version where this DeprecationWarning was introduced was 3.12.x - i.e [3.11.4](https://github.com/protocolbuffers/protobuf/blob/v3.11.4/python/google/protobuf/descriptor.py) is the last version that worked with the old format.

**Comment by viathor** [comment]
Note that #4751 will temporarily hide the deprecation warnings so they stop swamping our test outputs (BTW: other deprecation warnings appear to have sneaked into the crowd, e.g. from quimb). However, let's keep this issue open until a proper fix is possible (i.e. until upgrading protoc no longer breaks TFQ compatibility).

**Comment by MichaelBroughton** [comment]
For the record, this issue is no longer a TFQ issue. The remaining proto deprecation warnings are coming from the v1alpha1 protos that need to be re-generated internally using our gapic tools. The fix for this will involve someone going through the internal build instructions for the py_gapic rules we need and then copying the built artifacts out into Cirq.

**Comment by dstrain115** [comment]
@verult This issue would be resolved (in part by) the GAPIC regeneration.

**Comment by 95-martin-orion** [comment]
From @MichaelBroughton: "Once GAPIC is resolved this is done"

**Comment by maffoo** [comment]
GAPIC code was updated in #5139. Can someone check if this is fixed?
