### ISSUE TITLE
Simulator cannot be initialized with PerQubitDepolarizingWithDampedReadoutNoiseModel

### ISSUE THREAD

**Issue by asmuzsoy** [quantumlib/Cirq#4170]
**Description of the issue**

A Simulator object should be able to be initialized with any NOISE_MODEL_LIKE object, but the following error is raised when a PerQubitDepolarizingWithDampedReadoutNoiseModel object is passed in as the noise parameter.

```
Traceback (most recent call last):
  File "attempt.py", line 93, in <module>
    simulator = cirq.sim.Simulator(noise = noise_model)
  File "/usr/local/google/home/asuzsoy/anaconda3/lib/python3.8/site-packages/cirq/sim/sparse_simulator.py", line 158, in __init__
    raise ValueError(f'noise must be unitary or mixture but was {noise_model}')
ValueError: noise must be unitary or mixture but was <cirq_google.experimental.noise_models.noise_models.PerQubitDepolarizingWithDampedReadoutNoiseModel object at 0x7f23ba3f08e0>

```

**How to reproduce the issue**

The simple_noise_from_calibration_metrics method from cirq-google/cirq_google/experimental/noise_models/noise_models.py returns a PerQubitDepolarizingWithDampedReadoutNoiseModel object. When this is passed into the Simulator constructor, the error is produced.
```

noise_model = simple_noise_from_calibration_metrics(calibration=calibration, depol_noise = True)

simulator = cirq.sim.Simulator(noise = noise_model)

```

**Cirq version**
0.11.0

**Comment by daxfohl** [comment]
Correct, the state vector simulator has only limited noise support. You can use DensityMatrixSimulator to simulate larger categories of noise models.

**Comment by 95-martin-orion** [comment]
Hey @daxfohl, I think the logic we added here was due to a mistake on my part. The sparse simulator and other state vector-based simulators actually _can_ accept channel-based noise, thanks to the channel support in `act_on_state_vector_args` [here](https://github.com/quantumlib/Cirq/blob/8e7e302b944135b0946c10374480681b6a7b0d9d/cirq-core/cirq/sim/act_on_state_vector_args.py#L219). This uses "trajectory-like" behavior for channels, which is consistent with how we currently treat mixtures.

**Comment by 95-martin-orion** [comment]
Assigned to @asmuzsoy as an introduction to creating PRs in Cirq.
