### ISSUE TITLE
circuit.insert_at_frontier crashes when inserting GlobalPhaseOperation

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#4225]
**Description of the issue**
`circuit.insert_at_frontier` fails when trying to insert `GlobalPhaseOperation` because the operation does not have any qubits. As a result, `PointOptimizer` also fails when the `new_operations` contain a `GlobalPhaseOperation`. 

**How to reproduce the issue**

```
circuit = cirq.Circuit(cirq.X(q[0]))
circuit.insert_at_frontier(cirq.GlobalPhaseOperation(1j), 1)
```

<Output>

```bash
Traceback (most recent call last):
  File "/Users/tanujkhattar/opt/anaconda3/envs/cirq/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-59dcb891d749>", line 2, in <module>
    circuit.insert_at_frontier(cirq.GlobalPhaseOperation(1j), 1)
  File "/Users/tanujkhattar/quantum/Cirq/cirq-core/cirq/circuits/circuit.py", line 2119, in insert_at_frontier
    insertion_indices, _ = self._pick_inserted_ops_moment_indices(flat_ops, start, frontier)
  File "/Users/tanujkhattar/quantum/Cirq/cirq-core/cirq/circuits/circuit.py", line 2014, in _pick_inserted_ops_moment_indices
    op_start = max(start, max(frontier[q] for q in op.qubits))
ValueError: max() arg is an empty sequence
```

</Output>

**Cirq version**
0.12.0.dev

**Comment by cduck** [comment]
I just ran into this bug (and add a one-line fix for it in #4224).
