### ISSUE TITLE
Measurement Gate with Key cannot be printed

### ISSUE THREAD

**Issue by dretta** [quantumlib/Cirq#4479]
**Description of the issue**

Creating a Measurement Gate with a measurement key produces a non-string, making it unprintable.

**How to reproduce the issue**

```
>>> cirq.MeasurementGate(1)
cirq.MeasurementGate(1, '', ())
>>> cirq.MeasurementGate(1, cirq.MeasurementKey(name=''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/retta/.virtualenvs/cirq/lib/python3.9/site-packages/cirq/ops/measurement_gate.py", line 199, in __repr__
    f'{self.key!r}, '
  File "/usr/local/google/home/retta/.virtualenvs/cirq/lib/python3.9/site-packages/cirq/ops/measurement_gate.py", line 74, in key
    return str(self.mkey)
TypeError: __str__ returned non-string (type MeasurementKey)
>>> cirq.MeasurementGate(1, cirq.MeasurementKey(name='a'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/retta/.virtualenvs/cirq/lib/python3.9/site-packages/cirq/ops/measurement_gate.py", line 199, in __repr__
    f'{self.key!r}, '
  File "/usr/local/google/home/retta/.virtualenvs/cirq/lib/python3.9/site-packages/cirq/ops/measurement_gate.py", line 74, in key
    return str(self.mkey)
TypeError: __str__ returned non-string (type MeasurementKey)
>>> cirq.MeasurementKey(name='')
cirq.MeasurementKey(name=)
```

**Cirq version**
0.11.0
Branched off of https://github.com/quantumlib/Cirq/commit/58cda7a4f9718ef0bebd91950af192df8d47b0d6

**Comment by vtomole** [comment]
For what it's worth, the snippets you posted don't break on Cirq's mainline branch:

```python
(venv6) (base) vtomole@vtomole:~/Cirq$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cirq
>>> cirq.__version__
'0.13.0.dev'
>>> cirq.MeasurementGate(1)
cirq.MeasurementGate(1, cirq.MeasurementKey(name=''), ())
>>> cirq.MeasurementGate(1, cirq.MeasurementKey(name=''))
cirq.MeasurementGate(1, cirq.MeasurementKey(name=''), ())
>>> cirq.MeasurementGate(1, cirq.MeasurementKey(name='a'))
cirq.MeasurementGate(1, cirq.MeasurementKey(name='a'), ())
>>> cirq.MeasurementKey(name='')
cirq.MeasurementKey(name='')
```

You do have to provide a non-empty measurement key on the most recent release of Cirq though:

```python
(venv6) (base) vtomole@vtomole:~/Cirq$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cirq
>>> cirq.__version__
'0.12.0'
>>> cirq.MeasurementGate(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vtomole/venv6/lib/python3.8/site-packages/cirq/ops/measurement_gate.py", line 68, in __init__
    self.key = key  # type: ignore
  File "/home/vtomole/venv6/lib/python3.8/site-packages/cirq/ops/measurement_gate.py", line 82, in key
    self.mkey = value.MeasurementKey(name=key)
  File "<string>", line 5, in __init__
  File "/home/vtomole/venv6/lib/python3.8/site-packages/cirq/value/measurement_key.py", line 45, in __post_init__
    raise ValueError("Measurement key name cannot be empty")
ValueError: Measurement key name cannot be empty
```

@tanujkhattar  @smitsanghavi , should these changes have been deprecated instead?

**Comment by dabacon** [comment]
I believe this behavior was changed in #4445 which does an explicit check for isinstance of string.  Closing.
