### ISSUE TITLE
Implement general decomposition of 3-qubit unitary gates

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/Cirq#451]
This would allow ControlledGates made from 2-qubit KnownMatrixGates to automatically run on the simulator.

**Comment by Strilanc** [comment]
Relevant papers via cpoole, balint:

https://arxiv.org/pdf/quant-ph/0406176.pdf
https://arxiv.org/pdf/quant-ph/0401178.pdf

**Comment by aminjahanpour** [comment]
I am trying to implement a three-qubit gate in an eight-qubit circuit.

```
import cirq
import numpy as np

class CsAgate(cirq.ThreeQubitGate):
    def __init__(self, theta):
        self.theta = theta

    def _unitary_(self):
        st = np.sin(self.theta)
        ct = np.cos(self.theta)

        return np.array([
        [1., 0, 0, 0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, ct, st,0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, st,-ct,0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 1.,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    1., 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, ct,st, 0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, st,-ct,0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 1.,    0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        ]
        )


    def _circuit_diagram_info_(self, args):
        return 'o','theta({})'.format(round(self.theta, 2)), '0'

    def __str__(self):
        return 'test'

n_qubits = 8
qubits = cirq.LineQubit.range(n_qubits)
my_circuit=cirq.Circuit([CsAgate(2.)(qubits[0], qubits[1], qubits[2])])
print(my_circuit)
print(my_circuit.unitary())
```

The circuit is generated successfully but Cirq throws an error when calculating the circuit unitary.

```
Traceback (most recent call last):
  File "/Users/mjahanpo/Desktop/opt_api/test.py", line 46, in <module>
    print(my_circuit.unitary())
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/circuits/circuit.py", line 1418, in unitary
    result = _apply_unitary_circuit(self, state, qs, dtype)
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/circuits/circuit.py", line 1960, in _apply_unitary_circuit
    return protocols.apply_unitaries(
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/protocols/apply_unitary_protocol.py", line 492, in apply_unitaries
    result = apply_unitary(unitary_value=op,
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/protocols/apply_unitary_protocol.py", line 347, in apply_unitary
    result = strat(unitary_value, args)
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/protocols/apply_unitary_protocol.py", line 384, in _strat_apply_unitary_from_apply_unitary
    sub_result = func(sub_args)
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/ops/gate_operation.py", line 113, in _apply_unitary_
    return protocols.apply_unitary(self.gate, args, default=None)
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/protocols/apply_unitary_protocol.py", line 347, in apply_unitary
    result = strat(unitary_value, args)
  File "/Users/mjahanpo/opt/anaconda3/envs/opt_api/lib/python3.8/site-packages/cirq/protocols/apply_unitary_protocol.py", line 419, in _strat_apply_unitary_from_unitary
    matrix.reshape(val_qid_shape * 2),
ValueError: cannot reshape array of size 256 into shape (2,2,2,2,2,2)
```

**Comment by balopat** [comment]
@aminjahanpour your gate is a 4 qubit gate (2 ** 4 x 2 ** 4 = 16 x 16 matrix) and not 3 qubit gate. 

This works: 

<details>
```
import cirq
import numpy as np

class CsAgate(cirq.Gate):
    def __init__(self, theta):
        self.theta = theta

    def _num_qubits_(self) -> int:
        return 4

    def _unitary_(self):
        st = np.sin(self.theta)
        ct = np.cos(self.theta)

        return np.array([
        [1., 0, 0, 0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, ct, st,0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, st,-ct,0,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 1.,   0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    1., 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, ct,st, 0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, st,-ct,0,    0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 1.,    0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],

        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        [0, 0, 0, 0,    0, 0, 0, 0,     0, 0, 0, 0,     0, 0, 0, 0],
        ]
        )


    def _circuit_diagram_info_(self, args):
        return 'o','theta({})'.format(round(self.theta, 2)), '0', '0'

    def __str__(self):
        return 'test'

n_qubits = 8
qubits = cirq.LineQubit.range(n_qubits)
my_circuit=cirq.Circuit([CsAgate(2.)(qubits[0], qubits[1], qubits[2], qubits[3])])
print(my_circuit)
print(my_circuit.unitary())
```
</details>

However, if you don't mind I'd hide your comment as it is off topic for this issue. Thanks!

**Comment by balopat** [comment]
An update on this: #2873 basically has the solution, just needs a review (hint hint @quantumlib/cirq-maintainers).
