### ISSUE TITLE
Lint broken

### ISSUE THREAD

**Issue by dabacon** [quantumlib/Cirq#5383]
PR are failing lint due to a bug which looks unrelated to the PR.  [Example](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true)

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 108[7](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:8), in check
    check_parallel(
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:9).12/x64/lib/python3.8/site-packages/pylint/lint/parallel.py", line 148, in check_parallel
    jobs, initializer=initializer, initargs=[dill.dumps(linter)]
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 364, in dumps
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 336, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line [9](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:10)71, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/hostedtoolcache/Python/3.8.[12](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:13)/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 7[17](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:18), in save_reduce
    save(state)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 1[25](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:26)1, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 687, in save_reduce
    save(cls)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dill/_dill.py", line 1791, in save_type
    defaults = [obj._field_defaults[field] for field in obj._fields]
  File "/opt/hostedtoolcache/Python/3.8.12/x[64](https://github.com/quantumlib/Cirq/runs/6516853850?check_suite_focus=true#step:6:65)/lib/python3.8/site-packages/dill/_dill.py", line 1791, in <listcomp>
    defaults = [obj._field_defaults[field] for field in obj._fields]
KeyError: 'color'
Error: Process completed with exit code 1.
```

**Comment by dabacon** [comment]
Dill just got upgraded so my guess is that is the problem.

**Comment by dabacon** [comment]
Confirmed that bumping dill back fixes lint.

**Comment by dabacon** [comment]
But now notebook tests fail.  joy.

**Comment by dabacon** [comment]
There was a notebook that used cirq --pre but was not in the excluded list. I've added it there which fixes things. Need to investigate why that got through CI
