### ISSUE TITLE
`import cirq_google` fails with protobuf 4.21.0

### ISSUE THREAD

**Issue by cqc-alec** [quantumlib/Cirq#5407]
**Description of the issue**

With a fresh install of `cirq_google`, which pulls in `protobuf` 4.21.0, `import cirq_google` fails.

**How to reproduce the issue**

```
python -m venv env
. env/bin/activate
pip install cirq_google
python -c "import cirq_google"
```

<details>

Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alec/tmp/env/lib/python3.8/site-packages/cirq_google/__init__.py", line 19, in <module>
    from cirq_google import api
  File "/home/alec/tmp/env/lib/python3.8/site-packages/cirq_google/api/__init__.py", line 16, in <module>
    from cirq_google.api import v2
  File "/home/alec/tmp/env/lib/python3.8/site-packages/cirq_google/api/v2/__init__.py", line 16, in <module>
    from cirq_google.api.v2 import (
  File "/home/alec/tmp/env/lib/python3.8/site-packages/cirq_google/api/v2/batch_pb2.py", line 14, in <module>
    from . import program_pb2 as cirq__google_dot_api_dot_v2_dot_program__pb2
  File "/home/alec/tmp/env/lib/python3.8/site-packages/cirq_google/api/v2/program_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/alec/tmp/env/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

</details>

**Cirq version**

This is with `cirq_google` version 0.14.1.

**Comment by vtomole** [comment]
Thanks for opening this. Ithink this was fixed yesterday via https://github.com/quantumlib/Cirq/pull/5408


```
python -m venv env
. env/bin/activate
pip install pip install cirq_google==0.15.0.dev20220526140534
python -c "import cirq_google"
```

Doesn't error out.

**Comment by cqc-alec** [comment]
Yup, thanks!
