### ISSUE TITLE
`eval(repr(op))` fails for `cirq.SingleQubitCliffordGate`. 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Cirq#5641]
**Description of the issue**
See title. 

**How to reproduce the issue**

```python
>>> z_clifford = cirq.SingleQubitCliffordGate.from_pauli(cirq.Z).on(cirq.LineQubit(2))
>>> repr(z_clifford)
cirq.SingleQubitCliffordGate(X:-X, Y:-Y, Z:+Z).on(cirq.LineQubit(2))
>>> eval(repr(z_clifford))
Traceback (most recent call last):

  File "/usr/local/google/home/tanujkhattar/anaconda3/envs/cirq/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-14-99e3d364586d>", line 1, in <module>
    eval(repr(z_clifford))

  File "<string>", line 1
    cirq.SingleQubitCliffordGate(X:-X, Y:-Y, Z:+Z).on(cirq.LineQubit(2))
                                  ^
SyntaxError: invalid syntax
```

**Cirq version**
0.16dev

**Comment by vtomole** [comment]
Taking this.
