### ISSUE TITLE
Can't simulate a repeated `CircuitOperation` that contains a `repeat_until` `CircuitOperation`

### ISSUE THREAD

**Issue by vtomole** [quantumlib/Cirq#6446]
**Description of the issue**
Repetitively checking the syndromes of a prepared state before using it to measure stabilizers is an [important primitive for fault tolerance](https://courses.cs.washington.edu/courses/cse599d/06wi/lecturenotes19.pdf). True fault tolerance requires that this procedure happen multiple times. 

For a minimum reproducible example, measuring a qubit until it's `|0>` and then applying an `X` gate to it multiple times will throw a  ` raise ValueError('Infinite loop: condition is not modified in subcircuit.')`

**How to reproduce the issue**

```python
import cirq
import sympy

sim = cirq.Simulator()
q = cirq.LineQubit(0)
inner_loop = cirq.CircuitOperation(
    cirq.FrozenCircuit(cirq.H(q), cirq.measure(q, key="inner_loop")),
    use_repetition_ids=False,
    repeat_until=cirq.SympyCondition(sympy.Eq(sympy.Symbol("inner_loop"), 0)),
)
outer_loop = cirq.Circuit(inner_loop, cirq.X(q), cirq.measure(q, key="outer_loop"))

circuit = cirq.Circuit(cirq.CircuitOperation(cirq.FrozenCircuit(outer_loop), repetitions=2))
print(circuit)
result = sim.run(circuit, repetitions=1)
print(result)

```
Will print

`ValueError: Infinite loop: condition is not modified in subcircuit.`

<details>

0: ───[ 0: ───[ 0: ───H───M('inner_loop')─── ](no_rep_ids, until=Eq(inner_loop, 0))───X───M('outer_loop')─── ](loops=2)───
Traceback (most recent call last):
  File "/home/victory/research-superstaq/research_superstaq/compiler/quantinuum/test1.py", line 15, in <module>
    result = sim.run(circuit, repetitions=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/work/sampler.py", line 63, in run
    return self.run_sweep(program, param_resolver, repetitions)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/sim/simulator.py", line 72, in run_sweep
    return list(self.run_sweep_iter(program, params, repetitions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/sim/simulator.py", line 103, in run_sweep_iter
    records = self._run(
              ^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/sim/simulator_base.py", line 243, in _run
    split_into_matching_protocol_then_general(resolved_circuit, self._can_be_in_run_prefix)
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/sim/simulator.py", line 989, in split_into_matching_protocol_then_general
    if not predicate(op) or not qs.isdisjoint(blocked_qubits):
           ^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/sim/simulator_base.py", line 171, in _can_be_in_run_prefix
    return protocols.has_unitary(val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/has_unitary_protocol.py", line 103, in has_unitary
    result = strat(val)
             ^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/has_unitary_protocol.py", line 132, in _strat_has_unitary_from_decompose
    operations, _, _ = _try_decompose_into_operations_and_qubits(val)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/decompose_protocol.py", line 477, in _try_decompose_into_operations_and_qubits
    return decompose_once(val, None), val.qubits, qid_shape
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/decompose_protocol.py", line 381, in decompose_once
    decomposed = NotImplemented if method is None else method(*args, **kwargs)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 433, in _decompose_
    return self.mapped_circuit(deep=False).all_operations()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 416, in mapped_circuit
    circuits.Circuit(self._mapped_single_loop(rep) for rep in self.repetition_ids)
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit.py", line 1771, in __init__
    flattened_contents = tuple(ops.flatten_to_ops_or_moments(contents))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 134, in flatten_to_ops_or_moments
    yield from flatten_to_ops_or_moments(subtree)
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 133, in flatten_to_ops_or_moments
    for subtree in root:
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 416, in <genexpr>
    circuits.Circuit(self._mapped_single_loop(rep) for rep in self.repetition_ids)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 389, in _mapped_single_loop
    circuit = protocols.with_rescoped_keys(circuit, (repetition_id,))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/measurement_key_protocol.py", line 337, in with_rescoped_keys
    result = NotImplemented if getter is None else getter(path, bindable_keys or frozenset())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit.py", line 1007, in _with_rescoped_keys_
    new_moment = protocols.with_rescoped_keys(moment, path, bindable_keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/measurement_key_protocol.py", line 337, in with_rescoped_keys
    result = NotImplemented if getter is None else getter(path, bindable_keys or frozenset())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/moment.py", line 332, in _with_rescoped_keys_
    return Moment(
           ^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/moment.py", line 100, in __init__
    tuple(op_tree.flatten_to_ops(contents))
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 113, in flatten_to_ops
    yield from flatten_to_ops(subtree)
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/ops/op_tree.py", line 112, in flatten_to_ops
    for subtree in root:
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/moment.py", line 333, in <genexpr>
    protocols.with_rescoped_keys(op, path, bindable_keys) for op in self.operations
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/protocols/measurement_key_protocol.py", line 337, in with_rescoped_keys
    result = NotImplemented if getter is None else getter(path, bindable_keys or frozenset())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 643, in _with_rescoped_keys_
    return self.replace(parent_path=path, extern_keys=bindable_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 273, in replace
    return CircuitOperation(**kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/circuits/circuit_operation.py", line 213, in __init__
    raise ValueError('Infinite loop: condition is not modified in subcircuit.')
ValueError: Infinite loop: condition is not modified in subcircuit.

</details>

The alternative is to run the `CircuitOperation` twice, but this breaks the printing of the result

```python
import cirq
import sympy

sim = cirq.Simulator()
q = cirq.LineQubit(0)
inner_loop = cirq.CircuitOperation(
    cirq.FrozenCircuit(cirq.H(q), cirq.measure(q, key="inner_loop0")),
    use_repetition_ids=False,
    repeat_until=cirq.SympyCondition(sympy.Eq(sympy.Symbol("inner_loop0"), 0)),
)
inner_loop1 = cirq.CircuitOperation(
    cirq.FrozenCircuit(cirq.H(q), cirq.measure(q, key="inner_loop1")),
    use_repetition_ids=False,
    repeat_until=cirq.SympyCondition(sympy.Eq(sympy.Symbol("inner_loop1"), 0)),
)


outer_loop = cirq.Circuit(inner_loop, cirq.X(q), cirq.measure(q, key="outer_loop"))
outer_loop1 = cirq.Circuit(inner_loop1, cirq.X(q), cirq.measure(q, key="outer_loop1"))

circuit = cirq.Circuit(outer_loop, outer_loop1)
print(circuit)
result = sim.run(circuit, repetitions=1)
print(result)
```

Prints
```
0: ───[ 0: ───H───M('inner_loop0')─── ](no_rep_ids, until=Eq(inner_loop0, 0))───X───M('outer_loop')───[ 0: ───H───M('inner_loop1')─── ](no_rep_ids, until=Eq(inner_loop1, 0))───X───M('outer_loop1')───
Traceback (most recent call last):
  File "/home/victory/research-superstaq/research_superstaq/compiler/quantinuum/test.py", line 24, in <module>
    print(result)
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/study/result.py", line 391, in __str__
    return _keyed_repeated_bitstrings(self.measurements)
                                      ^^^^^^^^^^^^^^^^^
  File "/home/victory/research_superstaq_venv/lib/python3.11/site-packages/cirq/study/result.py", line 343, in measurements
    raise ValueError('Cannot extract 2D measurements for repeated keys')
ValueError: Cannot extract 2D measurements for repeated keys

```

**Cirq version**
`1.4.0.dev20240126200039`

**Comment by vtomole** [comment]
CC @dabacon  :)

**Comment by daxfohl** [comment]
I can't for the life of me remember how to set up the dev environment, but looking through the code, it looks like you _might_ be able to work around the first issue by setting `use_repetition_ids=False` in the outer loop as well. 

The bug appears to be in the `CircuitOperation._with_rescoped_keys_` implementation, as it rescopes all the measurement keys in the subcircuit but doesn't rescope the `repeat_until` key, so they no longer align. `repeat_until` is of type `Condition`, which has a `_with_rescoped_keys_` implementation, so it should just be a matter of forwarding on the call.

It looks like a number of other protocols in `CircuitOperation` should account for the keys in `repeat_until` condition too:  `_with_measurement_key_mapping_`, `_with_key_path_`, `_with_key_path_prefix_`.

As for the error printing the result, IIRC that was by design, but it wasn't my domain so I can't say for sure. Definitely seems like something to revisit though if it blocks this use case.

**Comment by telescopic** [comment]
@tanujkhattar / @verult  I'd like to take this up if possible

**Comment by vtomole** [comment]
Thanks for the offer @telescopic . I've assigned this to you.
