### ISSUE TITLE
TypeError: unhashable type: 'KrausChannel' when using merge_k_qubit_unitaries

### ISSUE THREAD

**Issue by jiannanWang** [quantumlib/Cirq#6503]
**Description of the issue**
Running merge_k_qubit_unitaries after dephase_measurements returns a TypeError: unhashable type: 'KrausChannel'. I feel this crash shouldn't happen since merge_k_qubit_unitaries should just skip KrausChannel if it can't merge it. From the documentation, there's no statement that these two transformers shouldn't be applied together. Please correct me if that is not the case.

Some other transformer function (in the comments) also returns the same error.

**How to reproduce the issue**

```
import cirq
qr = cirq.LineQubit.range(1)
qc = cirq.Circuit()
measurement_gate = cirq.measure(qr, key='result')
qc.append(measurement_gate)

qc = cirq.dephase_measurements(qc)

qc = cirq.merge_k_qubit_unitaries(qc, k=1)
# qc = merge_single_qubit_gates_to_phased_x_and_z(qc)
# qc = merge_single_qubit_gates_to_phxz(qc)

```

<details>

Traceback (most recent call last):
  File "/mnt/test_crash.py", line 9, in <module>
    qc = cirq.merge_k_qubit_unitaries(qc, k=1)
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_api.py", line 380, in func_with_logging
    return _transform_and_log(
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_api.py", line 439, in _transform_and_log
    transformed_circuit = _run_transformer_on_circuit(
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_api.py", line 425, in _run_transformer_on_circuit
    return func(mutable_circuit if mutable_circuit else circuit, **kwargs)
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/merge_k_qubit_gates.py", line 98, in merge_k_qubit_unitaries
    circuit = transformer_primitives.merge_k_qubit_unitaries_to_circuit_op(
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_primitives.py", line 606, in merge_k_qubit_unitaries_to_circuit_op
    return merge_operations_to_circuit_op(
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_primitives.py", line 567, in merge_operations_to_circuit_op
    return merge_operations(circuit, merge_func, tags_to_ignore=tags_to_ignore, deep=deep)
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_primitives.py", line 506, in merge_operations
    merged_circuit.add_op_to_moment(moment_idx, op)
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/transformers/transformer_primitives.py", line 346, in add_op_to_moment
    self.ops_by_index[moment_index][op] = 0
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/_compat.py", line 107, in wrapped_no_args
    object.__setattr__(self, cache_name, func(self))
  File "/root/anaconda3/envs/cirq/lib/python3.10/site-packages/cirq/value/value_equality_attr.py", line 88, in _value_equality_hash
    return hash((self._value_equality_values_cls_(), self._value_equality_values_()))
TypeError: unhashable type: 'KrausChannel'

</details>

**Cirq version**
You can get the cirq version by printing `cirq.__version__`. From the command line:

```
1.3.0
```

**Comment by NoureldinYosri** [comment]
the circuit contains measurements which means it's not equivalent to a unitary, instead it's a channel. Measurements are not unitary operations but channels.  `merge_k_qubit_unitaries` as its name implies assumes its inputs, `merge_single_qubit_gates_to_phased_x_and_z` also assumes unitaries since it will create a `PhasedXZGate` which is a unitary operation. 

what you need is `cirq.kraus` which will return the [kraus representation of a channel](https://en.wikipedia.org/wiki/Quantum_operation#Kraus_operators) e.g.
```py3
>>> cirq.kraus(cirq.measure(qr, key='result'))
(array([[1., 0.],
       [0., 0.]]), array([[0., 0.],
       [0., 1.]]))
```

note however that `cirq.kraus` doesn't support circuit inputs, if you want that you can file a feature request.
